question_data = [
{"type":"boolean","difficulty":"medium","category":"Entertainment: Video Games","question":"In Monster Hunter Generations, guild style is a type of hunting style.","correct_answer":"True","incorrect_answers":["False"]},{"type":"boolean","difficulty":"medium","category":"Science &amp; Nature","question":"Shrimp can swim backwards.","correct_answer":"True","incorrect_answers":["False"]},
{"type":"boolean","difficulty":"medium","category":"Sports","question":"Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.","correct_answer":"True","incorrect_answers":["False"]},{"type":"boolean","difficulty":"medium","category":"Entertainment: Film","question":"Joan Cusack starred in the 2009 disaster movie, &quot;2012&quot;.","correct_answer":"False","incorrect_answers":["True"]},
{"type":"boolean","difficulty":"medium","category":"Entertainment: Video Games","question":"&quot;Metal Gear Solid 3: Snake Eater&quot; takes place on Shadow Moses Island.","correct_answer":"False","incorrect_answers":["True"]},{"type":"boolean","difficulty":"medium","category":"Entertainment: Japanese Anime &amp; Manga","question":"In &quot;JoJo&#039;s Bizarre Adventure&quot;, Father Enrico Pucchi uses a total of 3 stands in Part 6: Stone Ocean.","correct_answer":"True","incorrect_answers":["False"]},
{"type":"boolean","difficulty":"medium","category":"Science: Mathematics","question":"111,111,111 x 111,111,111 = 12,345,678,987,654,321","correct_answer":"True","incorrect_answers":["False"]},
{"type":"boolean","difficulty":"medium","category":"Entertainment: Video Games","question":"The scrapped Sonic the Hedgehog 2 level &quot;Hidden Palace Zone&quot; was later reused in the iOS port of the game. ","correct_answer":"True","incorrect_answers":["False"]},
{"type":"boolean","difficulty":"medium","category":"History","question":"In 1967, a magazine published a story about extracting hallucinogenic chemicals from bananas to raise moral questions about banning drugs.","correct_answer":"True","incorrect_answers":["False"]},
{"type":"boolean","difficulty":"medium","category":"Entertainment: Music","question":"Nick Mason is the only member to appear on every Pink Floyd album.","correct_answer":"True","incorrect_answers":["False"]}
]
